# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PFC_Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *



class Ui_MainWindow(object):

    total = None
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Калькулятор БЖУ")
        MainWindow.setWindowTitle("LLL")
        MainWindow.resize(749, 472)
        MainWindow.setStyleSheet("background-color: rgb(255, 179, 71);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Weight = QtWidgets.QLabel(self.centralwidget)
        self.label_Weight.setGeometry(QtCore.QRect(60, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Weight.setFont(font)
        self.label_Weight.setObjectName("label_Weight")
        self.label_Height = QtWidgets.QLabel(self.centralwidget)
        self.label_Height.setGeometry(QtCore.QRect(180, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Height.setFont(font)
        self.label_Height.setObjectName("label_Height")
        self.label_Age = QtWidgets.QLabel(self.centralwidget)
        self.label_Age.setGeometry(QtCore.QRect(300, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Age.setFont(font)
        self.label_Age.setObjectName("label_Age")
        self.radioBTN_iMan = QtWidgets.QRadioButton(self.centralwidget)
        self.radioBTN_iMan.setGeometry(QtCore.QRect(410, 50, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioBTN_iMan.setFont(font)
        self.radioBTN_iMan.setCheckable(True)
        self.radioBTN_iMan.setObjectName("radioBTN_iMan")
        self.radioBTN_iWoman = QtWidgets.QRadioButton(self.centralwidget)
        self.radioBTN_iWoman.setGeometry(QtCore.QRect(560, 50, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioBTN_iWoman.setFont(font)
        self.radioBTN_iWoman.setObjectName("radioBTN_iWoman")
        self.radioBTN_iWoman.setCheckable(True)
        self.spinBox_inputAge = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_inputAge.setGeometry(QtCore.QRect(280, 50, 111, 22))
        self.spinBox_inputAge.setObjectName("spinBox_inputAge")
        self.line_inputWeight = QtWidgets.QLineEdit(self.centralwidget)
        self.line_inputWeight.setGeometry(QtCore.QRect(20, 50, 113, 21))
        self.line_inputWeight.setObjectName("line_inputWeight")
        self.line_inputHeight = QtWidgets.QLineEdit(self.centralwidget)
        self.line_inputHeight.setGeometry(QtCore.QRect(150, 50, 113, 21))
        self.line_inputHeight.setObjectName("line_inputHeight")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-10, 80, 761, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 0, 761, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Slider = QtWidgets.QDial(self.centralwidget)
        self.Slider.setGeometry(QtCore.QRect(30, 310, 171, 121))
        self.Slider.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.Slider.setMinimum(1)
        self.Slider.setMaximum(5)
        self.Slider.setPageStep(10)
        self.Slider.setProperty("value", 1)
        self.Slider.setSliderPosition(1)
        self.Slider.setNotchTarget(1.0)
        self.Slider.setObjectName("Slider")
        self.label_KrutilkActivnosti = QtWidgets.QLabel(self.centralwidget)
        self.label_KrutilkActivnosti.setGeometry(QtCore.QRect(190, 350, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_KrutilkActivnosti.setFont(font)
        self.label_KrutilkActivnosti.setObjectName("label_KrutilkActivnosti")
        self.label_Activ0 = QtWidgets.QLabel(self.centralwidget)
        self.label_Activ0.setGeometry(QtCore.QRect(65, 420, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Activ0.setFont(font)
        self.label_Activ0.setObjectName("label_Activ0")
        self.label_Activ10 = QtWidgets.QLabel(self.centralwidget)
        self.label_Activ10.setGeometry(QtCore.QRect(145, 420, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Activ10.setFont(font)
        self.label_Activ10.setObjectName("label_Activ10")
        self.label_Activ5 = QtWidgets.QLabel(self.centralwidget)
        self.label_Activ5.setGeometry(QtCore.QRect(110, 290, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Activ5.setFont(font)
        self.label_Activ5.setObjectName("label_Activ5")
        self.label_Activ3 = QtWidgets.QLabel(self.centralwidget)
        self.label_Activ3.setGeometry(QtCore.QRect(50, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Activ3.setFont(font)
        self.label_Activ3.setObjectName("label_Activ3")
        self.label_Activ7 = QtWidgets.QLabel(self.centralwidget)
        self.label_Activ7.setGeometry(QtCore.QRect(165, 320, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Activ7.setFont(font)
        self.label_Activ7.setObjectName("label_Activ7")
        self.label_poyasnenie0 = QtWidgets.QLabel(self.centralwidget)
        self.label_poyasnenie0.setGeometry(QtCore.QRect(360, 365, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_poyasnenie0.setFont(font)
        self.label_poyasnenie0.setObjectName("label_poyasnenie0")
        self.label_Poyasnenie10 = QtWidgets.QLabel(self.centralwidget)
        self.label_Poyasnenie10.setGeometry(QtCore.QRect(360, 400, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Poyasnenie10.setFont(font)
        self.label_Poyasnenie10.setObjectName("label_Poyasnenie10")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(-3, 270, 761, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(583, 280, 20, 191))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(420, 110, 256, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.image_barbell = QtWidgets.QLabel(self.centralwidget)
        self.image_barbell.setGeometry(QtCore.QRect(590, 280, 161, 191))
        self.image_barbell.setText("")
        self.image_barbell.setPixmap(QtGui.QPixmap("C:/Users/TURBO/Downloads/de0ff864de319a480394c2b5c4279116.jpg"))
        self.image_barbell.setScaledContents(True)
        self.image_barbell.setObjectName("image_barbell")
        self.label_NormForFood_Text = QtWidgets.QLabel(self.centralwidget)
        self.label_NormForFood_Text.setGeometry(QtCore.QRect(20, 90, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_NormForFood_Text.setFont(font)
        self.label_NormForFood_Text.setObjectName("label_NormForFood_Text")
        self.label_Calory_Text = QtWidgets.QLabel(self.centralwidget)
        self.label_Calory_Text.setGeometry(QtCore.QRect(80, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Calory_Text.setFont(font)
        self.label_Calory_Text.setObjectName("label_Calory_Text")
        self.label_Protein_Text = QtWidgets.QLabel(self.centralwidget)
        self.label_Protein_Text.setGeometry(QtCore.QRect(80, 160, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Protein_Text.setFont(font)
        self.label_Protein_Text.setObjectName("label_Protein_Text")
        self.label_Fat_Text = QtWidgets.QLabel(self.centralwidget)
        self.label_Fat_Text.setGeometry(QtCore.QRect(80, 190, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Fat_Text.setFont(font)
        self.label_Fat_Text.setObjectName("label_Fat_Text")
        self.label_Carbon_Text = QtWidgets.QLabel(self.centralwidget)
        self.label_Carbon_Text.setGeometry(QtCore.QRect(80, 220, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Carbon_Text.setFont(font)
        self.label_Carbon_Text.setObjectName("label_Carbon_Text")
        self.label_Carbon = QtWidgets.QLabel(self.centralwidget)
        self.label_Carbon.setGeometry(QtCore.QRect(30, 220, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Carbon.setFont(font)
        self.label_Carbon.setObjectName("label_Carbon")
        self.label_Fat = QtWidgets.QLabel(self.centralwidget)
        self.label_Fat.setGeometry(QtCore.QRect(30, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Fat.setFont(font)
        self.label_Fat.setObjectName("label_Fat")
        self.label_Calory = QtWidgets.QLabel(self.centralwidget)
        self.label_Calory.setGeometry(QtCore.QRect(30, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Calory.setFont(font)
        self.label_Calory.setObjectName("label_Calory")
        self.label_Protein = QtWidgets.QLabel(self.centralwidget)
        self.label_Protein.setGeometry(QtCore.QRect(30, 160, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Protein.setFont(font)
        self.label_Protein.setObjectName("label_Protein")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 150, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(85, 170, 255);\n"
                                      "selection-background-color: rgb(85, 255, 255);\n"
                                      "alternate-background-color: rgb(0, 170, 127);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)




        self.pushButton.clicked.connect(self.clicked_letsGo)

    def clicked_letsGo(self):
        try:
            weihgt = int(self.line_inputWeight.text())
            height = int(self.line_inputHeight.text())
            age = int(self.spinBox_inputAge.text())
            calory_sum = int(10 * weihgt + 6.25 * height - 5 * age)
            self.total = calory_sum

            if self.radioBTN_iMan.isChecked():
                self.total += 5
            else:
                self.total -= 161

            if self.Slider.value() == 1:
                self.total *= 1.2
            elif self.Slider.value() == 2:
                self.total *= 1.375
            elif self.Slider.value() == 3:
                self.total *= 1.55
            elif self.Slider.value() == 4:
                self.total *= 1.7
            else:
                self.total *= 1.9

            self.label_Calory.setText(str(round(self.total)))
            self.PFC_norms()


        except:
            print("error")

    def PFC_norms(self):
        protein = self.total * 0.3 / 4
        carbon = self.total * 0.4 / 4
        fat = self.total * 0.3 / 9

        self.label_Protein.setText(str(round(protein)))
        self.label_Carbon.setText(str(round(carbon)))
        self.label_Fat.setText(str(round(fat)))


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор БЖУ"))

        self.label_Weight.setText(_translate("MainWindow", "Вес"))
        self.label_Height.setText(_translate("MainWindow", "Рост"))
        self.label_Age.setText(_translate("MainWindow", "Возраст"))
        self.radioBTN_iMan.setText(_translate("MainWindow", "Я МУЖЧИНА"))
        self.radioBTN_iWoman.setText(_translate("MainWindow", "Я ЖЕНЩИНА"))
        self.label_KrutilkActivnosti.setText(_translate("MainWindow", "Крутилка уровня   \n"
                                                                      "    активности"))
        self.label_Activ0.setText(_translate("MainWindow", "0"))
        self.label_Activ10.setText(_translate("MainWindow", "10"))
        self.label_Activ5.setText(_translate("MainWindow", "5"))
        self.label_Activ3.setText(_translate("MainWindow", "3"))
        self.label_Activ7.setText(_translate("MainWindow", "7"))
        self.label_poyasnenie0.setText(_translate("MainWindow", "\"0\" - полное отсутствие движений"))
        self.label_Poyasnenie10.setText(_translate("MainWindow", "\"10\" - Да ты просто, Бульдозер"))
        self.label_NormForFood_Text.setText(_translate("MainWindow", "Норма для тебя по еде это:"))
        self.label_Calory_Text.setText(_translate("MainWindow", "калорий"))
        self.label_Protein_Text.setText(_translate("MainWindow", "белка"))
        self.label_Fat_Text.setText(_translate("MainWindow", "жирка"))
        self.label_Carbon_Text.setText(_translate("MainWindow", "углеводов"))
        self.label_Carbon.setText(_translate("MainWindow", "0"))
        self.label_Fat.setText(_translate("MainWindow", "0"))
        self.label_Calory.setText(_translate("MainWindow", "0"))
        self.label_Protein.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "Let`s go"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
